### ISSUE TITLE
Cannot change ros2 topic frequency

### ISSUE THREAD

**Issue by SangHunHan92** [SBG-Systems/sbg_ros2_driver#20]
Hi.

I run ```ros2 launch sbg_driver sbg_device_launch.py``` and want to get topic like ```/sbg/imu_data```, ```/imu/data```.

First of all, the strange thing I'm experiencing is that the above topic comes in at 10Hz and not 25Hz.
After, I changed ```log_imu_data``` in ```sbg_device_uart_default.yaml``` by incrementing and decrementing it, but topic frequency don't change. It seems that the frequency is output regardless of the parameter.
I also changed ```baudRate``` from ```115200``` to ```921600```, but the problem hasn't been resolved.

![image](https://github.com/SBG-Systems/sbg_ros2_driver/assets/38457117/b1ef72b1-b7bf-4920-907d-86a49d944244)

![image](https://github.com/SBG-Systems/sbg_ros2_driver/assets/38457117/99e227e6-02c8-40d9-ad54-21cd180b1878)

![image](https://github.com/SBG-Systems/sbg_ros2_driver/assets/38457117/9f8203f6-5288-48a9-8dbd-0c4532a8edff)

What was the problem?

PS: I am connecting via USB and receiving data through ttyUSB0 port. Could this be a problem?

**Comment by benmakka** [comment]
Hello @SangHunHan92,
The baudrate cannot be configured through the driver; instead, the sbgCenter or sbgECom library should be used for this purpose.

Regarding the output frequency for the `/sbg/imu_data` topic, could you confirm that `ConfWithRos` parameter is set to `True` ? If it is already configured as such, could you further confirm what is returned by the command `ros2 topic hz /sbg/imu_data` ?

Please note that the rostopic `/imu/data` a standard ROS message topic, limited to 25 Hz. However, you can access the same data at higher frequencies via the` /sbg/imu_data` topic.

**Comment by SangHunHan92** [comment]
I set ```ConfWithRos=True```, and it works well.

Thanks !!

**Comment by kbnh101** [comment]
<img width="1527" height="417" alt="Image" src="https://github.com/user-attachments/assets/be53ac1b-ce07-48ce-ab6a-8481783b6b12" />
<img width="1917" height="455" alt="Image" src="https://github.com/user-attachments/assets/822f2c95-7e57-44a0-b885-ca6a24d3c53d" />

I encountered the same issue, so I checked the SBG Data Logger as shown in the picture. Sometimes the SBG publishes data at 180 Hz, but it usually publishes at around 30 Hz. How can I fix the output frequency?
