### ISSUE TITLE
never configure leverArmX,leverArmY,leverArmZ in ConfigApplier::configureImuAlignement method

### ISSUE THREAD

**Issue by pierreopti** [SBG-Systems/sbg_ros2_driver#27]
Section imuAlignementLeverArm:
      # X Primary lever arm in IMU X axis (once IMU alignment is applied) m 
      leverArmX: xxxx
      # Y Primary lever arm in IMU Y axis (once IMU alignment is applied) m 
      leverArmY: yyyy
      # Z Primary lever arm in IMU Z axis (once IMU alignment is applied) m 
      leverArmZ: zzzz

Theses 3 parameters are not taken and applied from configuration file.
The function ConfigApplier::configureImuAlignement get parameters from device , compare with new parameters and set the device parameter with the call sbgEComCmdSensorSetAlignmentAndLeverArm.
But this call is done with geted parameters not with new parameters.

Suggested change of config_applier.cpp is : 
```cpp
@@ -130,7 +130,7 @@ void ConfigApplier::configureImuAlignement(const SbgEComSensorAlignmentInfo& ref
   || !areEquals(sensor_alignement.misPitch, ref_sensor_align.misPitch)
   || !areEquals(sensor_alignement.misYaw, ref_sensor_align.misYaw))
   {
-    error_code = sbgEComCmdSensorSetAlignmentAndLeverArm(&m_ref_sbg_com_handle, &ref_sensor_align, level_arms_vector.data());
+    error_code = sbgEComCmdSensorSetAlignmentAndLeverArm(&m_ref_sbg_com_handle, &ref_sensor_align, ref_level_arms.data());
 
     checkConfigurationApplied(error_code, std::string("IMU alignement"));
   }
```

**Comment by richibrics** [comment]
Hi, what about log_gps1_pos ? Setting it to 2 doesn't change the frequency for me; it's always publishing both "/imu/nav_sat_fix" and "sbg/gps_pos" at 4Hz (node frequency is set to 400Hz).
It seems like the log_gps1_pos is never set on the device.
