### ISSUE TITLE
Enhancement with ros2 control support

### ISSUE THREAD

**Issue by tomlogan501** [SBG-Systems/sbg_ros2_driver#3]
HI,
I was wandering if this driver can be used or derivative for ros2 control with [imu_sensor_broadcaster](https://github.com/ros-controls/ros2_controllers/tree/master/imu_sensor_broadcaster)
Would it be better for a better performance and behavior ?

**Comment by tolesam** [comment]
Hi @tomlogan501 
As long as imu_sensor_broadcaster is based on strandard /imu topics it can be used with sbg_ros2_driver which publishes on these same topics.
