### ISSUE TITLE
remove earth rotation and gravity

### ISSUE THREAD

**Issue by zoidberg77** [SBG-Systems/sbg_ros2_driver#34]
Hi is it possible to remove earth rotation and gravity from the IMU or odometry data from within the package?

**Comment by tolesam** [comment]
Hello @zoidberg77 ,
Thank you for your feedback.
This information is not available on ROS driver https://github.com/SBG-Systems/sbg_ros_driver but is available in sbgECom EKF_ROT_ACCEL messages.
We'll implement it for ROS2 in https://github.com/SBG-Systems/sbg_ros2_driver (issue transferred).

**Comment by tolesam** [comment]
Hello @zoidberg77 ,
The requested information is now available in the topic `/sbg/ekf_rot_accel_body` .
