### ISSUE TITLE
ros-galactic-sbg-driver missing from upstream repositories

### ISSUE THREAD

**Issue by bverhagen** [SBG-Systems/sbg_ros2_driver#4]
In the README it is mentioned that `ros-galactic-sbg-driver` is available in the upstream ROS2 repositories. However, while I am able to find `ros-foxy-sbg-driver` in the http://packages.ros.org/ros2/ubuntu repository, the Galactic version seems to be missing.

Is there a different upstream repository that offers this pre-built binary package for Ubuntu Focal? Is it on the planning to add it to the above one?

Thank you for your information. For now, I will resort to a build from source.

**Comment by tolesam** [comment]
Hello @bverhagen 
Thank you for your feedback.
I've tried to get `ros-galactic-sbg-driver` and `ros-foxy-sbg-driver` in an official ROS docker, respectively `ros:galactic` and `ros:foxy`, and both apt-get install commands worked.
Can you verify your environment is configured for the right distribution?
