### ISSUE TITLE
Imu/odometry orientation wrong using sbg/quat output on ENU

### ISSUE THREAD

**Issue by tomlogan501** [SBG-Systems/sbg_ros2_driver#5]
Hi,
During tests, I notice an issue with the orientation of the output odometry when you define the parameters  `log_ekf_quat`

I end up using only `log_ekf_euler` for the good orientation, using  the other set an offset of 90°.

Is it an issue with the direct use of the sbg_quat message in ENU convention ?

Regards

**Comment by samprt-heracles** [comment]
Hello,

Do you have any update on this issue ? I am observing the same behavior.

**Comment by rsiryani** [comment]
It should have been fixed with the latest rework around NED/ENU convention.
https://github.com/SBG-Systems/sbg_ros2_driver/pull/16
